### ISSUE TITLE
READ Me with instructions

### ISSUE THREAD

**Issue by venkatamandala** [iChekun/restful_bsuir_mobile_online_store#1]
Hello, i am getting error on running your client app

I did npm install
then I did npm start. i am getting MODULE_NOT_FOUND react-app-rewired config-overrides.js.

Can you help provide the steps? thanks

**Comment by IlyaChakun** [comment]
Hello mate! Actually app building with webpack, so we have webpack configs. Therefore for starting you need to write  npm run dev. Why dev? if you will come to package.json you will see place with scripts. There we pull up webpack server with dev profile. Also you can run up from package json with tupping on green arrow(on picture) 
![image](https://user-images.githubusercontent.com/48980016/77405665-8e801e00-6dc4-11ea-8759-4d7c7149aabd.png)
